import { Injectable } from "@nestjs/common";
import { Response } from "express";
import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";

export interface ExportColumn {
  header: string;
  key: string;
  width?: number;
}

@Injectable()
export class ExportService {
  async exportCsv(
    res: Response,
    filename: string,
    columns: ExportColumn[],
    rows: Record<string, unknown>[],
  ) {
    res.setHeader("Content-Type", "text/csv; charset=utf-8");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${filename}.csv"`,
    );

    const header = columns.map((c) => `"${c.header}"`).join(",");
    res.write("﻿" + header + "\n");

    for (const row of rows) {
      const line = columns
        .map((c) => {
          const val = row[c.key];
          if (val == null) return '""';
          const str = String(val).replace(/"/g, '""');
          return `"${str}"`;
        })
        .join(",");
      res.write(line + "\n");
    }

    res.end();
  }

  async exportXlsx(
    res: Response,
    filename: string,
    columns: ExportColumn[],
    rows: Record<string, unknown>[],
    sheetName = "Sheet1",
  ) {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = "UniERP";
    workbook.created = new Date();

    const sheet = workbook.addWorksheet(sheetName);

    sheet.columns = columns.map((c) => ({
      header: c.header,
      key: c.key,
      width: c.width || 20,
    }));

    // Style header row
    const headerRow = sheet.getRow(1);
    headerRow.font = { bold: true };
    headerRow.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF4472C4" },
    };
    headerRow.font = { bold: true, color: { argb: "FFFFFFFF" } };

    for (const row of rows) {
      sheet.addRow(row);
    }

    res.setHeader(
      "Content-Type",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    );
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${filename}.xlsx"`,
    );

    await workbook.xlsx.write(res);
    res.end();
  }

  async exportPdf(
    res: Response,
    filename: string,
    columns: ExportColumn[],
    rows: Record<string, unknown>[],
    title?: string,
  ) {
    const doc = new PDFDocument({
      margin: 40,
      size: "A4",
      layout: "landscape",
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${filename}.pdf"`,
    );

    doc.pipe(res);

    // Title
    if (title) {
      doc.fontSize(16).font("Helvetica-Bold").text(title, { align: "center" });
      doc.moveDown(0.5);
    }

    doc.fontSize(8).font("Helvetica");

    // Table header
    const colWidth = (doc.page.width - 80) / columns.length;
    let x = 40;
    const y = doc.y;

    doc.font("Helvetica-Bold");
    for (const col of columns) {
      doc.text(col.header, x, y, { width: colWidth, continued: false });
      x += colWidth;
    }
    doc.moveDown(0.3);
    doc
      .moveTo(40, doc.y)
      .lineTo(doc.page.width - 40, doc.y)
      .stroke();
    doc.moveDown(0.3);

    doc.font("Helvetica");

    for (const row of rows) {
      if (doc.y > doc.page.height - 60) {
        doc.addPage();
      }

      x = 40;
      const rowY = doc.y;
      for (const col of columns) {
        const val = row[col.key];
        doc.text(val != null ? String(val) : "", x, rowY, {
          width: colWidth,
          continued: false,
        });
        x += colWidth;
      }
      doc.moveDown(0.2);
    }

    // Footer
    doc
      .fontSize(7)
      .text(
        `Generated by UniERP on ${new Date().toISOString().slice(0, 10)}`,
        40,
        doc.page.height - 30,
        { align: "center" },
      );

    doc.end();
  }
}
